steps:
  - name: ":docker:"
    plugins:
      docker-compose#v2.4.1:
        build: test

  - wait

steps:
  - command: node --version
    plugins:
      docker-compose#v2.4.1:
        image: "node:7"
        workdir: /app