steps:
  - name: ":docker:"
    plugins:
      docker-compose#v2.4.1:
        build: test
  - wait

steps:
  - command: ls && node --version
    plugins:
      docker-compose#v2.4.1:
       run: test
       